
molecule-generate:
	molecule init scenario --scenario-name default -r db -d vagrant

molecule-create:
	molecule create

molecule-list:
	molecule list

molecule-login:
	molecule login -h instance

molecule-converge:
	molecule converge

molecule-verify:
	molecule verify
