---
- name: Configure App
  hosts: app
  become: true
  roles:
    - app
    - role: jdauphant.nginx
      nginx_error_log_level: info
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
        - error_log "/var/log/nginx/error.log"
      nginx_sites:
        default:
          - listen {{ default_port }}
          - server_name {{ default_server_name }}
          - location / {
                proxy_pass http://127.0.0.1:{{ reddit_port }};
            }
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
