---
- name: Deploy Puma application
  hosts: app
  become: true
  tasks:
    - name: Clean reddit app dir
      file:
        state: absent
        path: /home/appuser/reddit

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit

  handlers:
    - name: reload puma
      service: name=puma state=restarted
