all:
  hosts:
    appserver:
      ansible_host: 35.187.114.173
    dbserver:
      ansible_host: 35.205.210.83
  children:
    app:
      hosts:
        appserver:
    db:
      hosts:
        dbserver:
