all:
  hosts:
    appserver:
      ansible_host: 35.240.112.108
    dbserver:
      ansible_host: 35.205.227.19
  children:
    app:
      hosts:
        appserver:
    db:
      hosts:
        dbserver:
