---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      notify: restart mongod

  handlers:
    - name: restart mongod
      service: name=mongod state=restarted

- name: Configure App
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.132.0.37
  tasks:
    - name: Stopped and disabled reddit unit in systemcd
      systemd:
        name: reddit
        state: stopped
        enabled: no
      register: service_reddit_status

    - name: Kill reddit process
      shell: "lsof -t -i:9292 | xargs kill -9"
      when: service_reddit_status.changed == True

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: Enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      service: name=puma state=restarted

- name: Deploy Puma application
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: Clean reddit app dir
      file:
        state: absent
        path: /home/appuser/reddit

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/appuser/reddit
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit

  handlers:
    - name: reload puma
      service: name=puma state=restarted
